from Performance_burning.srfd_lib import swg
from Performance_burning.srfd_lib import amp
import sys
import numpy
import math
import csv
import time

def visa_binary(data):
    header_len = int(chr(data[1]))
    num_bytes = int(data[2:2+header_len].decode('ascii'))
    payload = data[2+header_len:2+header_len+num_bytes]
    waveform = numpy.frombuffer(payload, dtype=numpy.float64)
    return waveform

def config_vna(mxo3):
    mxo3.write("*RST")
    mxo3.write("CHANnel1:BANDwidth 350E6")
    mxo3.write("CHANnel1:COUPling DC")
    mxo3.write("CHANnel1:SCALe 0.1")
    mxo3.write("TIMebase:SCALe 0.0005")
    mxo3.write("TIMebase:HORizontal:POSition 0.002")
    mxo3.write("TRIGger:MODE NORMal")
    mxo3.write("TRIGger:ANEDge:LEVel 0.8")
    mxo3.write("TRIGger:ANEDge:COUPling DC")
    mxo3.write("TRIGger:EVENt1:SOURce EXTernanalog")
    mxo3.write("TRIGger:ACTions:OUT:PLENgth 0.008")
    mxo3.write("TRIGger:ACTions:OUT:SOURce ONTRigger")
    mxo3.write("TRIGger:ACTions:OUT:STATe ON")

def fidelity_test (mxo3, swg33522B, swg33611A, srfd_com):
    print()
    print("Starting fidelity test")
    mxo3.write("*RST")
    mxo3.write("CHANnel1:COUPling DC")
    mxo3.write("TRIGger:MODE NORMal")
    mxo3.write("TRIGger:EVENt1:SOURce EXTernanalog")
    mxo3.write("TRIGger:ANEDge:LEVel 0.8")
    mxo3.write("TRIGger:ANEDge:COUPling DC")
    mxo3.write("CHANnel1:SCALe 0.3")
    mxo3.write("CHANnel1:BANDwidth 350E6")
    mxo3.write("TIMebase:SCALe 1E-3")
    mxo3.write("TIMebase:HORizontal:POSition 0.0045")
    mxo3.write("ACQuire:SRAte:MODe MAN")
    mxo3.write("ACQuire:SRAte 5E9")
    mxo3.write("ACQuire:POINTs:MODE MAN")
    mxo3.write("ACQuire:POINTs 50000000")
    mxo3.write("TRIGger:MODE SINGLe")
    mxo3.query("*OPC?")
    swg.config_fidelity (swg33522B, swg33611A)
    amp.standby(srfd_com)
    swg.on(swg33522B, swg33611A)
    amp.body_mode(srfd_com)
    amp.operate(srfd_com)
    print("Waiting for the amplifier to heat up", end="")
    for i in range(20):
        time.sleep(1)
        print(".", end="")
        sys.stdout.flush()
    print(" done")
    print("getting first sample")
    mxo3.query("RUNSINGle;*OPC?")
    mxo3.write("FORMat:DATA REAL,64")
    mxo3.write("CHANnel1:DATA:VALues? 5000000,40000000")
    frame1 = visa_binary(mxo3.read_raw())
    print("getting second sample")
    mxo3.query("RUNSINGle;*OPC?")
    mxo3.write("FORMat:DATA REAL,64")
    mxo3.write("CHANnel1:DATA:VALues? 5000000,40000000")
    frame2 = visa_binary(mxo3.read_raw())
    print("getting thrid sample")
    mxo3.query("RUNSINGle;*OPC?")
    mxo3.write("FORMat:DATA REAL,64")
    mxo3.write("CHANnel1:DATA:VALues? 5000000,40000000")
    frame3 = visa_binary(mxo3.read_raw())
    print("getting fourth sample")
    mxo3.query("RUNSINGle;*OPC?")
    mxo3.write("FORMat:DATA REAL,64")
    mxo3.write("CHANnel1:DATA:VALues? 5000000,40000000")
    frame4 = visa_binary(mxo3.read_raw())
    swg.off(swg33522B, swg33611A)
    amp.poweroff(srfd_com)
    print("saving in csv file...", end="")
    sys.stdout.flush()
    time_array = numpy.linspace(0,0.008, 40000000)
    with open("C:\\Users\\NP700007626\\Downloads\\fidelity.csv", mode='w', newline='') as file:
        writer = csv.writer(file)
        writer.writerow(['Time (s)','Voltage 1 (V)', 'Voltage 2 (V)','Voltage 3 (V)', 'Voltage 4 (V)'])
        for t1, v1, v2, v3, v4 in zip(time_array, frame1, frame2, frame3, frame4):
            writer.writerow([t1, v1, v2, v3, v4])
    print(" done")
    
def intermodulation_measure (mxo3, swg33522B, swg33611A, srfd_com):
    print()
    print("Starting intermodulation measure")
    mxo3.write("*RST")
    mxo3.write("CHANnel1:COUPling DC")
    mxo3.write("TRIGger:MODE NORMal")
    mxo3.write("TRIGger:EVENt1:SOURce EXTernanalog")
    mxo3.write("TRIGger:ANEDge:LEVel 0.8")
    mxo3.write("TRIGger:ANEDge:COUPling DC")
    mxo3.write("CHANnel1:SCALe 0.4")
    mxo3.write("TIMebase:SCALe 1E-3")
    mxo3.write("TIMebase:HORizontal:POSition 0.004")
    mxo3.write("ACQuire:SRAte:MODe MAN")
    mxo3.write("ACQuire:SRAte 5E9")
    mxo3.write("ACQuire:POINTs:MODE MAN")
    mxo3.write("ACQuire:POINTs 50000000")
    mxo3.write("TRIGger:MODE SINGLe")
    mxo3.write("CHANnel1:BANDwidth 350E6")
    mxo3.write("CALCulate:SPECtrum1:STATe ON")
    mxo3.write("CALCulate:SPECtrum1:SOURce C1")
    mxo3.write("CALCulate:SPECtrum1:FREQuency:STARt 60E6")
    mxo3.write("CALCulate:SPECtrum1:FREQuency:STOP 68E6")
    mxo3.write("CALCulate:SPECtrum1:GATE:POSition 4E-3")
    mxo3.write("CALCulate:SPECtrum1:GATE:WIDTh 2.8E-3")
    mxo3.query("*OPC?")
    swg.config_intermodulation(swg33522B, swg33611A)
    amp.standby(srfd_com)
    swg.on(swg33522B, swg33611A)
    amp.body_mode(srfd_com)
    amp.operate(srfd_com)
    mxo3.query("RUNSINGle;*OPC?")
    amp.standby(srfd_com)
    swg.off(swg33522B, swg33611A)
    mxo3.write("FORM ASC")
    mxo3.write("CALCulate:SPECtrum1:WAVeform:NORMal:DATA:VALues?")
    raw_fft = mxo3.read()
    data_fft = [float(val) for val in raw_fft.strip().split(',')]
    fft_data_array = numpy.array(data_fft)
    intermodul_array = numpy.concatenate((fft_data_array[:19200],fft_data_array[19700:]))
    fondamental = numpy.max(fft_data_array)
    intermodul = numpy.max(intermodul_array)
    intermodulation = fondamental - intermodul
    return intermodulation
    
def harmonic_output_measure (mxo3, swg33522B, swg33611A, srfd_com):
    print()
    print("Starting harmonic output measure")
    sys.stdout.flush()
    mxo3.write("*RST")
    mxo3.write("CHANnel1:COUPling DC")
    mxo3.write("TRIGger:MODE NORMal")
    mxo3.write("TRIGger:EVENt1:SOURce EXTernanalog")
    mxo3.write("TRIGger:ANEDge:LEVel 0.8")
    mxo3.write("TRIGger:ANEDge:COUPling DC")
    mxo3.write("CHANnel1:SCALe 0.4")
    mxo3.write("TIMebase:SCALe 1E-3")
    mxo3.write("TIMebase:HORizontal:POSition 0.004")
    mxo3.write("ACQuire:SRAte:MODe MAN")
    mxo3.write("ACQuire:SRAte 5E9")
    mxo3.write("ACQuire:POINTs:MODE MAN")
    mxo3.write("ACQuire:POINTs 50000000")
    mxo3.write("TRIGger:MODE SINGLe")
    # mxo3.write("TRIGger:ACTions:OUT:PLENgth 0.008")
    # mxo3.write("TRIGger:ACTions:OUT:SOURce ONTRigger")
    # mxo3.write("TRIGger:ACTions:OUT:STATe ON")
    mxo3.write("CHANnel1:BANDwidth 350E6")
    mxo3.write("CALCulate:SPECtrum1:STATe ON")
    mxo3.write("CALCulate:SPECtrum1:SOURce C1")
    mxo3.write("CALCulate:SPECtrum1:FREQuency:STARt 50E6")
    mxo3.write("CALCulate:SPECtrum1:FREQuency:STOP 300E6")
    mxo3.write("CALCulate:SPECtrum1:GATE:POSition 4E-3")
    mxo3.write("CALCulate:SPECtrum1:GATE:WIDTh 2.8E-3")
    mxo3.query("*OPC?")
    swg.config_harmonic_output (swg33522B, swg33611A)
    amp.standby(srfd_com)
    swg.on(swg33522B, swg33611A)
    amp.body_mode(srfd_com)
    amp.operate(srfd_com)
    mxo3.query("RUNSINGle;*OPC?")
    amp.standby(srfd_com)
    swg.off(swg33522B, swg33611A)
    mxo3.write("FORM ASC")
    mxo3.write("CALCulate:SPECtrum1:WAVeform:NORMal:DATA:VALues?")
    raw_fft = mxo3.read()
    data_fft = [float(val) for val in raw_fft.strip().split(',')]
    fft_data_array_harmonic = numpy.array(data_fft)
    fondamental_array = fft_data_array_harmonic[:100000]
    harmoniques_array = fft_data_array_harmonic[100000:]
    fondamental = numpy.max(fondamental_array)
    harmonique = numpy.max(harmoniques_array)
    harmonic_output = abs(fondamental - harmonique)
    return harmonic_output
     
def single_pulse_measure (mxo3, swg33522B, swg33611A, srfd_com):
    print()
    print("Starting single pulse measure")
    mxo3.write("*RST")
    mxo3.write("CHANnel1:COUPling DC")
    mxo3.write("TRIGger:MODE NORMal")
    mxo3.write("TRIGger:EVENt1:SOURce EXTernanalog")
    mxo3.write("TRIGger:ANEDge:LEVel 0.8")
    mxo3.write("TRIGger:ANEDge:COUPling DC")
    mxo3.write("CHANnel1:SCALe 0.4")
    mxo3.write("TIMebase:SCALe 1E-3")
    mxo3.write("CHANnel1:BANDwidth 350E6")
    mxo3.write("TIMebase:HORizontal:POSition 0.004")
    mxo3.write("ACQuire:SRAte:MODe MAN")
    mxo3.write("ACQuire:SRAte 5E9")
    mxo3.write("ACQuire:POINTs:MODE MAN")
    mxo3.write("ACQuire:POINTs 50000000")
    mxo3.write("TRIGger:MODE SINGLe")
    # mxo3.write("TRIGger:ACTions:OUT:PLENgth 0.008")
    # mxo3.write("TRIGger:ACTions:OUT:SOURce ONTRigger")
    # mxo3.write("TRIGger:ACTions:OUT:STATe ON")
    mxo3.query("*OPC?")
    swg.config_single_pulse(swg33522B, swg33611A)
    amp.standby(srfd_com)
    amp.body_mode(srfd_com)
    swg.on(swg33522B, swg33611A)
    amp.operate(srfd_com)
    mxo3.query("RUNSINGle;*OPC?")
    amp.standby(srfd_com)
    swg.off(swg33522B, swg33611A)
    print("Waiting for the scope to calculate the cycle RMS... ", end="")
    sys.stdout.flush()
    mxo3.write("MEASurement1:ENABLe ON")
    mxo3.write("MEASurement1:MAIN CYCRms")
    mxo3.write("MEASurement1:SOURCe C1")
    mxo3.write("MEASurement1:TRACk:STATe ON")
    mxo3.query("*OPC?")
    print("done")
    print("getting data from the mxo3... ", end="")
    sys.stdout.flush()
    mxo3.write("FORMat:DATA REAL,64")
    mxo3.write("MEASurement1:TRACk:DATA:VALues? 10000000,30000000")
    data_tr1 = visa_binary(mxo3.read_raw())
    print("done")
    min_rms = numpy.min(data_tr1)
    max_rms = numpy.max(data_tr1)
    output_power = 10 * math.log10( numpy.mean(data_tr1)**2 / 50 ) + 60 + 30
    gain_variation = 20 * math.log10(max_rms / min_rms)
    return gain_variation, output_power
    
def noise_unblanked (mxo3, swg33522B, swg33611A, srfd_com):
    mxo3.write("*RST")
    mxo3.write("CHANnel1:COUPling DC")
    mxo3.write("TRIGger:MODE NORMal")
    mxo3.write("TRIGger:EVENt1:SOURce EXTernanalog")
    mxo3.write("TRIGger:ANEDge:LEVel 0.8")
    mxo3.write("TRIGger:ANEDge:COUPling DC")
    mxo3.write("CHANnel1:SCALe 0.005")
    mxo3.write("TIMebase:SCALe 1E-2")
    mxo3.write("TIMebase:HORizontal:POSition 0.03")
    mxo3.write("ACQuire:SRAte:MODe MAN")
    mxo3.write("ACQuire:SRAte 5E9")
    mxo3.write("ACQuire:POINTs:MODE MANual")
    mxo3.write("ACQuire:POINTs:VALue 500E6")
    mxo3.write("TRIGger:MODE SINGLe")
    mxo3.write("CHANnel1:BANDwidth 1E8")
    mxo3.write("CALCulate:SPECtrum1:SOURce C1")
    mxo3.write("CALCulate:SPECtrum1:FREQuency:STARt 63.585E6")
    mxo3.write("CALCulate:SPECtrum1:FREQuency:STOP 64.135E6")
    mxo3.write("CALCulate:SPECtrum1:GATE:STARt 0")
    mxo3.write("CALCulate:SPECtrum1:GATE:Stop 0.06")
    mxo3.write("CALCulate:SPECtrum1:MAGNitude:LEVel -70")
    mxo3.write("CALCulate:SPECtrum1:STATe ON")
    mxo3.query("*OPC?")
    swg.config_noise(swg33522B, swg33611A)
    amp.operate(srfd_com)
    swg.on(swg33522B, swg33611A)
    mxo3.query("RUNSINGle;*OPC?")
    amp.standby(srfd_com)
    swg.off(swg33522B, swg33611A)
    mxo3.write("FORM ASC")
    mxo3.write("CALCulate:SPECtrum1:WAVeform:NORMal:DATA:VALues?")
    raw_fft = mxo3.read()
    data_fft = [float(val) for val in raw_fft.strip().split(',')]
    fft_data_array_harmonic = numpy.array(data_fft)
    max_noise = numpy.max(fft_data_array_harmonic)-30-15+60 # a 60 dB coupler is used
    return max_noise
    
def output_cond_setup (scope):
    scope.write("*RST")
    scope.write("CHANnel1:COUPling DC")
    scope.write("CHANnel2:COUPling DC")
    scope.write("CHANnel3:COUPling DC")
    scope.write("CHANnel4:COUPling DC")
    scope.write("TRIGger:MODE NORMal")
    scope.write("CHANnel1:BANDwidth 350E6")
    scope.write("CHANnel2:BANDwidth 350E6")
    scope.write("CHANnel3:BANDwidth 350E6")
    scope.write("CHANnel4:BANDwidth 350E6")
    scope.write("TRIGger:EVENt1:SOURce EXTernanalog")
    scope.write("TRIGger:ANEDge:LEVel 0.8")
    scope.write("TRIGger:ANEDge:COUPling DC")
    scope.write("TIMebase:SCALe 1E-8")
    scope.write("CHANnel1:SCALe 1")
    scope.write("CHANnel2:SCALe 0.004")
    scope.write("CHANnel3:SCALe 0.001")
    scope.write("CHANnel4:SCALe 0.004")
    scope.write("CHANnel1:STATe ON")
    scope.write("CHANnel2:STATe ON")
    scope.write("CHANnel3:STATe ON")
    scope.write("CHANnel4:STATe ON")
    scope.write("MEASurement1:MAIN CYCRms")
    scope.write("MEASurement1:SOURce C1")
    scope.write("MEASurement2:MAIN CYCRms")
    scope.write("MEASurement2:SOURce C2")
    scope.write("MEASurement3:MAIN CYCRms")
    scope.write("MEASurement3:SOURce C3")
    scope.write("MEASurement4:MAIN CYCRms")
    scope.write("MEASurement4:SOURce C4")
    scope.write("ACQuire:TYPE AVERage")
    scope.write("ACQuire:COUNt 100")
    scope.query("*OPC?")