ERROR_CODES = {
    "00": "NO ERROR",
    "40": "POWER LOSS – Amplifier internal power loss, condition; I/F still active",
    "41": "POWER SUPPLY FAULT - Amplifier high voltage, power supply failure",
    "42": "DUTY CYCLE – Maximum UNBLANK duty cycle exceeded",
    "43": "CURRENT OVERLOAD - Instantaneous peak current, in RF device(s) exceeds spec",
    "44": "DEVICE FAULT – RF device shorted",
    "45": "HV LOW – Amplifier high voltage power supply voltage dropped below specified minimum",
    "46": "HV HIGH – Amplifier high voltage power supply voltage went above specified limit",
    "48": "DRIVE - RF Drive level to amp exceeds specification",
    "49": "HEAT – RF heat sink temperature exceeds specification",
    "4A": "PEAK POWER – Peak power from amplifier exceeds specification",
    "4B": "AVG PWR – Average power from amplifier exceeds specification",
    "4C": "VSWR - Load VSWR exceeds specification",
    "4D": "GATE - Unblank gate length exceeds specification",
    "4E": "JUNCTION TEMPERATURE - RF device junction temperature exceeds specification",
    "4F": "UNDEFINED FAULT - All other RF Amplifier faults",
    "32": "HV RELAY LOW - Power monitor 1 or 2 fault; safety limit allowed for scan parameters has been reached",
    "20": "OVERHEAT - SRFD II Module has exceeded maximum operating temperature",
    "22": "CABLE FAULT - Bad or disconnected internal cable",
    "30": "POWER MONITOR 1 FAULT - Safety limit allowed for scan parameters has been reached",
    "31": "POWER MONITOR 2 FAULT - Safety limit allowed for scan parameters has been reached",
    "50": "WATCHDOG TIMER FAILURE",
    "51": "WATCHDOG CLOCK MONITOR FAILURE",
    "52": "UNRECOVERABLE FIRMWARE ERROR - Unimplemented instruction trap",
    "53": "UNRECOVERABLE FIRMWARE ERROR - Software interrupt",
    "54": "UNRECOVERABLE FIRMWARE ERROR - Unused Timer channel",
    "55": "UNRECOVERABLE FIRMWARE ERROR - Unused Pulse accumulator",
    "56": "UNRECOVERABLE FIRMWARE ERROR - ATD (Analog-to-Digital Converter) interrupt",
    "57": "UNRECOVERABLE FIRMWARE ERROR - BDLC (Byte Data Link Communications) interrupt",
    "58": "UNRECOVERABLE FIRMWARE ERROR - RAM broken",
    "59": "UNRECOVERABLE FIRMWARE ERROR - Undefined State",
    "5A": "UNRECOVERABLE FIRMWARE ERROR - Reserved for future firmware errors",
    "5B": "UNRECOVERABLE FIRMWARE ERROR - Reserved for future firmware errors",
    "5C": "UNRECOVERABLE FIRMWARE ERROR - Reserved for future firmware errors",
    "5D": "UNRECOVERABLE FIRMWARE ERROR - Reserved for future firmware errors",
    "5E": "UNRECOVERABLE FIRMWARE ERROR - Reserved for future firmware errors",
    "5F": "UNRECOVERABLE FIRMWARE ERROR - Reserved for future firmware errors"
}

ERROR_HINTS = {
    "00": "Aucune erreur détectée.",
    "40": "Alimentation interne coupée.",
    "41": "Problème d’alimentation haute tension.",
    "42": "Temps d’activation trop long.",
    "43": "Courant trop élevé.",
    "44": "Défaut matériel interne.",
    "45": "Tension trop basse.",
    "46": "Tension trop haute.",
    "48": "Signal d’entrée trop fort.",
    "49": "Température trop élevée.",
    "4A": "Puissance instantanée trop élevée.",
    "4B": "Puissance moyenne trop élevée.",
    "4C": "Mauvaise charge connectée.",
    "4D": "Durée d’activation trop longue.",
    "4E": "Température interne excessive.",
    "4F": "Défaut interne non identifié.",
    "32": "Limite de sécurité atteinte.",
    "20": "Module trop chaud.",
    "22": "Câble interne débranché ou défectueux.",
    "30": "Limite de sécurité atteinte (moniteur 1).",
    "31": "Limite de sécurité atteinte (moniteur 2).",
    "50": "Défaillance du système interne.",
    "51": "Défaillance du contrôle interne.",
    "52": "Erreur interne du logiciel.",
    "53": "Erreur interne du logiciel.",
    "54": "Erreur interne du logiciel.",
    "55": "Erreur interne du logiciel.",
    "56": "Erreur interne du logiciel.",
    "57": "Erreur interne du logiciel.",
    "58": "Mémoire interne défectueuse.",
    "59": "État interne invalide.",
    "5A": "Erreur interne.",
    "5B": "Erreur interne.",
    "5C": "Erreur interne.",
    "5D": "Erreur interne.",
    "5E": "Erreur interne.",
    "5F": "Erreur interne."
}

def decode_error(code: str) -> str:
    code = code.strip().upper()
    return ERROR_CODES.get(code, "Code d’erreur inconnu")
